# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabletest.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QTableWidget


# class EditableTableWidget(QTableWidget):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#
#     def mousePressEvent(self, event):
#         # 获取单击位置的项
#         item = self.itemAt(event.pos())
#         if item is not None:
#             # 设置当前项为编辑状态
#             self.setCurrentItem(item)
#             item.setEditable(True)
#             item.setFlags(item.flags() | Qt.ItemIsEditable)
#             self.editItem(item)
#         else:
#             super().mousePressEvent(event)
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        # self.tableWidget = EditableTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 5)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 4, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 2, 1, 1)
        # self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton_6.setObjectName("pushButton_6")
        # self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_xlsx = QtWidgets.QAction(MainWindow)
        self.action_xlsx.setObjectName("action_xlsx")
        self.menu.addAction(self.action_xlsx)
        self.action_xlsx1 = QtWidgets.QAction(MainWindow)
        self.action_xlsx1.setObjectName("action_xlsx1")
        self.menu.addAction(self.action_xlsx1)
        self.action_xlsx2 = QtWidgets.QAction(MainWindow)
        self.action_xlsx2.setObjectName("action_xlsx2")
        self.menu.addAction(self.action_xlsx2)
        self.action_xlsx3 = QtWidgets.QAction(MainWindow)
        self.action_xlsx3.setObjectName("action_xlsx3")
        self.menu.addAction(self.action_xlsx3)
        self.action_xlsx4 = QtWidgets.QAction(MainWindow)
        self.action_xlsx4.setObjectName("action_xlsx4")
        self.menu.addAction(self.action_xlsx4)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "空调测试用例编写工具"))
        self.pushButton.setText(_translate("MainWindow", "查看报文解析"))
        self.pushButton_2.setText(_translate("MainWindow", "添加步骤"))
        self.pushButton_3.setText(_translate("MainWindow", "清空"))
        self.pushButton_4.setText(_translate("MainWindow", "导出测试用例"))
        self.pushButton_5.setText(_translate("MainWindow", "添加备注"))
        # self.pushButton_6.setText(_translate("MainWindow", "添加章节"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.action_xlsx.setText(_translate("MainWindow", "导入协议文件"))
        self.action_xlsx1.setText(_translate("MainWindow", "导入测试用例"))
        self.action_xlsx2.setText(_translate("MainWindow", "导入map文件"))
        self.action_xlsx3.setText(_translate("MainWindow", "导入功能规范"))
        self.action_xlsx4.setText(_translate("MainWindow", "导出自动测试Excel"))
